url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jay Zheng" # the name of your site, e.g. ACME Corp.
author:
    email: "jz2384@cornell.edu"
social:
    github: "Juribu"
    linkedin: "william-ma-156ba4137"